### ISSUE TITLE
Subscribe to Volume / Mute Changes

### ISSUE THREAD

**Issue by hrueger** [m1dugh/native-sound-mixer#17] opened 2022-08-17 10:11 UTC
Hi @m1dugh,
first of all, thanks for this library. It's working great.

Do you think it is possible to add a feature to be able to subscribe to changes of Volume / Mute?

The Device class could become an `EventEmitter` and emit `mute` or `volumeChanged` Events.

**Comment by m1dugh** [comment] 2022-08-18 15:54
I'll be working on it but you can still make a pull request.

**Comment by hrueger** [comment] 2022-08-18 16:08
Thanks a lot 👌 Unfortunately, I don't know enough C++ to make that happen ;-)

**Comment by m1dugh** [comment] 2022-12-16 02:21
I pushed event listening on develop. For now it is undocumented, I'll document it as soon as I can, it works more or less like an EventEmitter. Therefore, it implements `on` and `removeListener` methods, and the signals emitted are `mute` and `volume`. As of now, it only works on windows and can be prone to bugs I couldn't find yet.

**Comment by hrueger** [comment] 2022-12-16 06:47
Very cool 👍 Thanks for your work. I'm currently trying it out.

One thing I noticed is that when `console.log`ging a `Device`, it does not show its properties anymore.
Before (on `master`):
![grafik](https://user-images.githubusercontent.com/18656830/208038183-5273496b-9225-4bfd-b31c-9e2351337da7.png)
(and so on)

Now (on `develop`):
![grafik](https://user-images.githubusercontent.com/18656830/208038253-fc5e8a4c-3ce1-4dd9-b755-ae45af76a47d.png)

This was done using `console.log(require("native-sound-mixer").default.devices)`.

All the properties (e.g. `devices[0].name`) work fine, though. It's not a big deal, I just though I'd mention it.

Regarding the events:
They're working great for me. The only strange thing I can see is that I get every event twice:
![grafik](https://user-images.githubusercontent.com/18656830/208039081-dcc90a9d-cf14-4ec7-a98f-f1476c5a9648.png)

<details>
<summary>Code</summary>

```JS
const nsm = require("native-sound-mixer").default;

console.log("Starting up");

const devices = nsm.devices;
console.log("Devices: ", devices);
const defaultOutput = nsm.getDefaultDevice(0);
const defaultInput = nsm.getDefaultDevice(1);

defaultOutput.on("volume", (volume) => {
    console.log("Volume changed: ", volume);
});
defaultOutput.on("mute", (muted) => {
    console.log("Muted changed: ", muted);
});
```

However, despite this bug, it's already so much better than polling 👍👍

**Comment by m1dugh** [comment] 2022-12-16 09:37
It no longer shows the property, bit they can still be called, it is because in the background, the properties are updated, the attributes still exist but are now accessors.

**Comment by hrueger** [comment] 2022-12-16 09:59
Ah, makes sense 👍

**Comment by m1dugh** [comment] 2022-12-16 17:26
This bug is surprising, I had it, and after i recompiled it worked perferctly fine, it might be some error in the code but maybe try recompiling from develop, in which the listener has been merged.

**Comment by hrueger** [comment] 2022-12-16 18:05
OK, I'll try that tomorrow.

**Comment by hrueger** [comment] 2022-12-17 09:47
Hm, I still have the same issue with the duplicate events. I'm using the `develop` branch and ran `git pull`, `npm run clean` and `npm run build`. That should have fixed the bug, right?

Another strange thing I noticed: When I start the script (same code as above) and mute my default output, I get a `volume` event with the value `true`?
![grafik](https://user-images.githubusercontent.com/18656830/208236037-e747971e-7246-4ee5-86c0-5895a1fc2c55.png)
After that, everything is working as it should (apart from the duplicate events).

**Comment by m1dugh** [comment] 2022-12-17 10:07
Ok I guess there might be some overlapping identifiers in your device names the way I identify devices, I'll fix that tomorrow. It might be the same bug causing the volume callback to trigger when the mute event is emitted.

**Comment by hrueger** [comment] 2022-12-17 10:24
Here's my Device List if that helps.
<details><summary>Code</summary>

```JS
const nsm = require("native-sound-mixer").default;

console.log("Starting up");

const devices = nsm.devices;
console.log("Devices: ", devices);
const defaultOutput = nsm.getDefaultDevice(0);
const defaultInput = nsm.getDefaultDevice(1);

console.table(devices.map((d) => ({name: d.name, type: ["out", "in"][d.type], isDefault: d.name === defaultOutput.name || d.name === defaultInput.name })).sort((a, b) => a.name.localeCompare(b.name)));
```
</details>

```
┌─────────┬──────────────────────────────────────────────────────────┬───────┬───────────┐
│ (index) │                           name                           │ type  │ isDefault │
├─────────┼──────────────────────────────────────────────────────────┼───────┼───────────┤
│    0    │            'Lautsprecher (Realtek(R) Audio)'             │ 'out' │   true    │
│    1    │             'Lautsprecher (Waves SoundGrid)'             │ 'out' │   false   │
│    2    │         'Line In /Microphone (Waves SoundGrid)'          │ 'in'  │   true    │
│    3    │ 'VoiceMeeter Aux Input (VB-Audio VoiceMeeter AUX VAIO)'  │ 'out' │   false   │
│    4    │ 'VoiceMeeter Aux Output (VB-Audio VoiceMeeter AUX VAIO)' │ 'in'  │   false   │
│    5    │     'VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)'      │ 'out' │   false   │
│    6    │     'VoiceMeeter Output (VB-Audio VoiceMeeter VAIO)'     │ 'in'  │   false   │
│    7    │  'VoiceMeeter VAIO3 Input (VB-Audio VoiceMeeter VAIO3)'  │ 'out' │   false   │
│    8    │ 'VoiceMeeter VAIO3 Output (VB-Audio VoiceMeeter VAIO3)'  │ 'in'  │   false   │
│    9    │          'VP249 (NVIDIA High Definition Audio)'          │ 'out' │   false   │
│   10    │          'VP249 (NVIDIA High Definition Audio)'          │ 'out' │   false   │
└─────────┴──────────────────────────────────────────────────────────┴───────┴───────────┘
```

**Comment by m1dugh** [comment] 2022-12-20 23:13
It should be fixed on develop

**Comment by hrueger** [comment] 2022-12-21 09:39
The `volume` `true` bug is now fixed, however, all events still appear twice.

**Comment by m1dugh** [comment] 2022-12-21 19:26
I finally might have spotted the problem (as I was able to reproduce it), it was a stupid thing creating duplicate events when calling `getDefaultDevice`.

**Comment by hrueger** [comment] 2022-12-22 15:21
Duplicate events are hone now 👍
However, I just got the `volume` `true` bug again...
![grafik](https://user-images.githubusercontent.com/18656830/209165973-0e7f75b0-5a93-4864-80d0-a9a9b6d9da30.png)

<details>
<summary>Code</summary>

```ts
const nsm = require("native-sound-mixer").default;

console.log("Starting up");

const devices = nsm.devices;
console.log("Devices: ", devices);
const defaultOutput = nsm.getDefaultDevice(0);
const defaultInput = nsm.getDefaultDevice(1);

console.table(devices.map((d) => ({name: d.name, type: ["out", "in"][d.type], isDefault: d.name === defaultOutput.name || d.name === defaultInput.name })).sort((a, b) => a.name.localeCompare(b.name)));

defaultOutput.on("volume", (volume) => {
    console.log("Volume changed: ", volume);
});
defaultOutput.on("mute", (muted) => {
    console.log("Muted changed: ", muted);
});
```

</details>

**Comment by m1dugh** [comment] 2022-12-22 16:13
I tried to solve it on another branch `fix-bad-callbacks-in-windows-events`. Since I'm not able to reproduce the bug I can't tell whether it is fixed or not. However, I guess this can be triggered when a device triggers at the same time a `mute` and `volume` event in the background, leading the 2 callbacks to take the same payload.

**Comment by hrueger** [comment] 2022-12-22 16:18
Interesting. Now I get this:
![grafik](https://user-images.githubusercontent.com/18656830/209176899-5e3b9fab-5c86-4b04-8a72-f4dfbb39dfd5.png)
The volume value is correct, so I think we can leave it that way 👍
It also works if the volume is not at 100% when I mute the output. I think one event too much is not a big of a problem, what's your opinion on this?
Thanks for the quick fix by the way.

**Comment by m1dugh** [comment] 2022-12-22 17:43
I don't exactly get the problem above. The volume callback is called when volume is `100%` and device is unmuted. Is that it ?

**Comment by hrueger** [comment] 2022-12-22 17:50
Exactly. If the first thing I do after starting the script is to mute my audio, I also get a `volume` event with the current volume.
Interestingly, if I change the volume first and then mute my output, everything works as expected.

All those tests were done when starting the script with not muted outputs and then muting them. If I start with a muted output and then unmute it, I only get a `volume` event and no `mute` event.

If I start muted and then change the volume (which lets windows automatically unmute the device, I get this:
![grafik](https://user-images.githubusercontent.com/18656830/209195700-6f550219-3163-4455-9fe0-f3c8712a225b.png)

**Comment by m1dugh** [comment] 2022-12-22 18:17
I'll dig into it, thanks for the testing.

**Comment by m1dugh** [comment] 2022-12-22 21:35
It should be fixed, thanks for the detailed explanation of how to reproduce the bug, helped me out a lot.

**Comment by hrueger** [comment] 2022-12-23 07:02
Yes, now everything works great and as expected 👍

**Comment by m1dugh** [comment] 2022-12-23 08:26
I merged the branch into develop, I will publish the version tomorrow on npm registries.

**Closed** 2022-12-23 08:26 UTC

**Comment by hrueger** [comment] 2022-12-23 09:05
Sounds great, thanks a ton 👍

**Comment by m1dugh** [comment] 2022-12-28 19:37
I published the latest version to npm registry, The documentation can be found at `https://m1dugh.github.io/native-sound-mixer/master/`
